#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-molecule_docker
Version  : 1.1.0
Release  : 1
URL      : https://files.pythonhosted.org/packages/30/c1/d58e6a568dae0be27de734a631e3202d0b882542a6a2a19d7288d446fc1b/molecule-docker-1.1.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/30/c1/d58e6a568dae0be27de734a631e3202d0b882542a6a2a19d7288d446fc1b/molecule-docker-1.1.0.tar.gz
Summary  : Molecule aids in the development and testing of Ansible roles
Group    : Development/Tools
License  : MIT
Requires: pypi-molecule_docker-license = %{version}-%{release}
Requires: pypi-molecule_docker-python = %{version}-%{release}
Requires: pypi-molecule_docker-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(ansible_compat)
BuildRequires : pypi(docker)
BuildRequires : pypi(molecule)
BuildRequires : pypi(pip)
BuildRequires : pypi(py)
BuildRequires : pypi(requests)
BuildRequires : pypi(selinux)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(setuptools_scm)
BuildRequires : pypi(setuptools_scm_git_archive)
BuildRequires : pypi(wheel)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv

%description
**********************
Molecule Docker Plugin
**********************
.. image:: https://badge.fury.io/py/molecule-docker.svg
:target: https://badge.fury.io/py/molecule-docker
:alt: PyPI Package

%package license
Summary: license components for the pypi-molecule_docker package.
Group: Default

%description license
license components for the pypi-molecule_docker package.


%package python
Summary: python components for the pypi-molecule_docker package.
Group: Default
Requires: pypi-molecule_docker-python3 = %{version}-%{release}

%description python
python components for the pypi-molecule_docker package.


%package python3
Summary: python3 components for the pypi-molecule_docker package.
Group: Default
Requires: python3-core
Provides: pypi(molecule_docker)
Requires: pypi(ansible_compat)
Requires: pypi(docker)
Requires: pypi(molecule)
Requires: pypi(requests)
Requires: pypi(selinux)

%description python3
python3 components for the pypi-molecule_docker package.


%prep
%setup -q -n molecule-docker-1.1.0
cd %{_builddir}/molecule-docker-1.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1649787814
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-molecule_docker
cp %{_builddir}/molecule-docker-1.1.0/LICENSE %{buildroot}/usr/share/package-licenses/pypi-molecule_docker/82314adfc4f5f364b3443f5df8a3393fd2121964
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-molecule_docker/82314adfc4f5f364b3443f5df8a3393fd2121964

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
